version: "3.5"
services:
  postgres:
    container_name: postgres
    image: postgres:14.3-alpine
    environment:
      POSTGRES_DB: "first"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"