export enum EnvVariable {
  PORT = 'PORT',
  JWT_SECRET = 'JWT_SECRET',
  ACCESS_EXPIRES_IN = 'ACCESS_EXPIRES_IN',
  REFRESH_EXPIRES_IN = 'REFRESH_EXPIRES_IN',
  CLIENT_ID = 'CLIENT_ID',
  CLIENT_SECRET = 'CLIENT_SECRET',
  CALLBACK_URL = 'CALLBACK_URL',
  SESSION_SECRET = 'SESSION_SECRET',
}
